### ISSUE TITLE
Incompatibility with unstable jellyfin branch

### ISSUE THREAD

**Issue by vincejv** [jellyfin/jellyfin-plugin-tvdb#119]
So far all plugins I have installed only the TVDB one doesn't support the latest unstable version
Error logs

```c#
[13:19:32] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly TvDbSharper, Version=3.2.2.0, Culture=neutral, PublicKeyToken=null from /config/plugins/TheTVDB_10.0.0.0/TvDbSharper.dll
[13:19:32] [ERR] [1] Emby.Server.Implementations.Plugins.PluginManager: Failed to load assembly /config/plugins/TheTVDB_10.0.0.0/Jellyfin.Plugin.Tvdb.dll. This error occurs when a plugin references an incompatible version of one of the shared libraries. Disabling plugin
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load type 'MediaBrowser.Common.Plugins.IPluginServiceRegistrator' from assembly 'MediaBrowser.Common, Version=10.9.0.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'MediaBrowser.Controller.Plugins.IServerEntryPoint' from assembly 'MediaBrowser.Controller, Version=10.9.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at Emby.Server.Implementations.Plugins.PluginManager.LoadAssemblies()+MoveNext()
System.TypeLoadException: Could not load type 'MediaBrowser.Common.Plugins.IPluginServiceRegistrator' from assembly 'MediaBrowser.Common, Version=10.9.0.0, Culture=neutral, PublicKeyToken=null'.
System.TypeLoadException: Could not load type 'MediaBrowser.Controller.Plugins.IServerEntryPoint' from assembly 'MediaBrowser.Controller, Version=10.9.0.0, Culture=neutral, PublicKeyToken=null'.
[13:19:32] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN addresses: ["127.0.0.1/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
[13:19:32] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions: []

```

**Comment by crobibero** [comment]
Plugins are not supported for unstable Jellyfin versions.
