### ISSUE TITLE
[Issue]: Plugin erroring 502 and not pulling Metadata

### ISSUE THREAD

**Issue by JayOlsa** [jellyfin/jellyfin-plugin-tvdb#146]
Don't know how long this has been going on, but probably a while. Jellyfin doesnt pull any metadata from TVDB. I have the latest version of both Jellyfin server and the plugin. Running on Linux, no virtualisation.
log:
`[2024-05-24 08:07:12.922 +02:00] [ERR] "TvdbSeasonImageProvider" failed in GetImageInfos for type "Season" at "/raid/Shows/Bleach (2004)/S17"
HTTP Response: 

<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
</body>
</html>

Tvdb.Sdk.LanguagesException: The HTTP status code of the response was not expected (502).

Status: 502
Response: 
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
</body>
</html>

   at Tvdb.Sdk.LanguagesClient.GetAllLanguagesAsync(CancellationToken cancellationToken)
   at Jellyfin.Plugin.Tvdb.TvdbClientManager.GetLanguagesAsync(CancellationToken cancellationToken)
   at Jellyfin.Plugin.Tvdb.Providers.TvdbSeasonImageProvider.GetImages(BaseItem item, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.GetImages(BaseItem item, IRemoteImageProvider provider, String preferredLanguage, Boolean includeAllLanguages, CancellationToken cancellationToken, Nullable`1 type)
[2024-05-24 08:07:13.094 +02:00] [INF] Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/raid/Shows/Bleach (2004)/S17/Bleach - S17E25 - The Master.mkv\" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format"
[2024-05-24 08:07:20.923 +02:00] [ERR] Failed to retrieve episode with id "0", series id 0:"Bleach - S17E25 - The Master"
HTTP Response: 

<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
</body>
</html>`

**Comment by crobibero** [comment]
Looks like your server isn't able to access the tvdb. Nothing we can really do on the plugin to fix that, sorry.

**Comment by JayOlsa** [comment]
yeah it cannot be that as I've tried creating a test server on my main computer and tvdb errored 502 there also, even when I ran it through a VPN or changed my dns. I'm gonna try again today on my laptop offnetwork on a mobile hotspot to see if it is just an issue of my network.
