### ISSUE TITLE
TheTVDB 2.0.0.0: DI ordering failure at startup

### ISSUE THREAD

**Issue by BaronGreenback** [jellyfin/jellyfin-plugin-tvdb#15]
Am getting the following error on start-up. (Unstable with new plugin manager running)

It looks to be caused by TvdbClientManager not getting instantiated first.

Please close if i'm testing on an older version. 

Can reproduce if testing needed.

```
[14:02:12] [ERR] [1] Emby.Server.Implementations.ApplicationHost: Error creating Jellyfin.Plugin.Tvdb.Providers.TvdbEpisodeImageProvider
System.InvalidOperationException: Unable to resolve service for type 'Jellyfin.Plugin.Tvdb.TvdbClientManager' while attempting to activate 'Jellyfin.Plugin.T
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Emby.Server.Implementations.ApplicationHost.CreateInstanceSafe(Type type) in C:\Code\jellyfin\Emby.Server.Implementations\ApplicationHost.cs:line 411
[14:02:12] [ERR] [1] Emby.Server.Implementations.ApplicationHost: Error creating Jellyfin.Plugin.Tvdb.Providers.TvdbPersonImageProvider
System.InvalidOperationException: Unable to resolve service for type 'Jellyfin.Plugin.Tvdb.TvdbClientManager' while attempting to activate 'Jellyfin.Plugin.T
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Emby.Server.Implementations.ApplicationHost.CreateInstanceSafe(Type type) in C:\Code\jellyfin\Emby.Server.Implementations\ApplicationHost.cs:line 411
[14:02:12] [ERR] [1] Emby.Server.Implementations.ApplicationHost: Error creating Jellyfin.Plugin.Tvdb.Providers.TvdbSeasonImageProvider
System.InvalidOperationException: Unable to resolve service for type 'Jellyfin.Plugin.Tvdb.TvdbClientManager' while attempting to activate 'Jellyfin.Plugin.T
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Emby.Server.Implementations.ApplicationHost.CreateInstanceSafe(Type type) in C:\Code\jellyfin\Emby.Server.Implementations\ApplicationHost.cs:line 411
[14:02:12] [ERR] [1] Emby.Server.Implementations.ApplicationHost: Error creating Jellyfin.Plugin.Tvdb.Providers.TvdbSeriesImageProvider
System.InvalidOperationException: Unable to resolve service for type 'Jellyfin.Plugin.Tvdb.TvdbClientManager' while attempting to activate 'Jellyfin.Plugin.T
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Emby.Server.Implementations.ApplicationHost.CreateInstanceSafe(Type type) in C:\Code\jellyfin\Emby.Server.Implementations\ApplicationHost.cs:line 411
[14:02:12] [ERR] [1] Emby.Server.Implementations.ApplicationHost: Error creating Jellyfin.Plugin.Tvdb.Providers.TvdbEpisodeProvider
System.InvalidOperationException: Unable to resolve service for type 'Jellyfin.Plugin.Tvdb.TvdbClientManager' while attempting to activate 'Jellyfin.Plugin.T
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Emby.Server.Implementations.ApplicationHost.CreateInstanceSafe(Type type) in C:\Code\jellyfin\Emby.Server.Implementations\ApplicationHost.cs:line 411
[14:02:12] [ERR] [1] Emby.Server.Implementations.ApplicationHost: Error creating Jellyfin.Plugin.Tvdb.Providers.TvdbSeriesProvider
System.InvalidOperationException: Unable to resolve service for type 'Jellyfin.Plugin.Tvdb.TvdbClientManager' while attempting to activate 'Jellyfin.Plugin.T
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Emby.Server.Implementations.ApplicationHost.CreateInstanceSafe(Type type) in C:\Code\jellyfin\Emby.Server.Implementations\ApplicationHost.cs:line 411
```

**Comment by crobibero** [comment]
This doesn't happen for me as of https://github.com/jellyfin/jellyfin/commit/c8a89b0fe3e0d3ac62c4d291688dba2ab616b710

**Comment by BaronGreenback** [comment]
I'll download this source and build a debug instance from it - to see if i can shed any more light on it.

**Comment by BaronGreenback** [comment]
Bug fixed in pluginManager when DI implemented in plugin.
