### ISSUE TITLE
Can't get metadata properly if the episode's type is movie

### ISSUE THREAD

**Issue by 9bingyin** [jellyfin/jellyfin-plugin-tvdb#159]
The metadata for https://www.thetvdb.com/series/monogatari/seasons/dvd/9 cannot be fetched correctly, but the image can be fetched correctly
I just manually filled in the tvdbid in jellyfin's webui and still can't get the episode info properly, The error message is as follows
```
[16:43:14] [INF] [28] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/media/Anime/物語系列/Season 9/伤物语 S09E01.mkv" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
[16:43:14] [ERR] [28] Jellyfin.Plugin.Tvdb.Providers.TvdbEpisodeProvider: Failed to retrieve episode with id 4139150, series id 4139150:伤物语 S09E01
```
Could this have anything to do with the fact that the type I chose when creating the media library was "Shows"? although I haven't tried changing it to "Mixed Movies and Shows" (which would take a lot of time)

Here's a screenshot of my file directory and corresponding section

![image](https://github.com/jellyfin/jellyfin-plugin-tvdb/assets/37502927/7550164e-77b0-4e69-9339-9143ea577df1)

```
物語系列
├── Season 1
│   ├── season.nfo
│   ├── 化物语 S01E01-thumb.jpg
│   ├── 化物语 S01E01.mkv
│   ├── 化物语 S01E01.nfo
│   ├── 化物语 S01E02-thumb.jpg
│   ├── 化物语 S01E02.mkv
│   ├── 化物语 S01E02.nfo
│   ├── 化物语 S01E03-thumb.jpg
│   ├── 化物语 S01E03.mkv
│   ├── 化物语 S01E03.nfo
│   ├── 化物语 S01E04-thumb.jpg
│   ├── 化物语 S01E04.mkv
│   ├── 化物语 S01E04.nfo
│   ├── 化物语 S01E05-thumb.jpg
│   ├── 化物语 S01E05.mkv
│   ├── 化物语 S01E05.nfo
│   ├── 化物语 S01E06-thumb.jpg
│   ├── 化物语 S01E06.mkv
│   ├── 化物语 S01E06.nfo
│   ├── 化物语 S01E07-thumb.jpg
│   ├── 化物语 S01E07.mkv
│   ├── 化物语 S01E07.nfo
│   ├── 化物语 S01E08-thumb.jpg
│   ├── 化物语 S01E08.mkv
│   ├── 化物语 S01E08.nfo
│   ├── 化物语 S01E09-thumb.jpg
│   ├── 化物语 S01E09.mkv
│   ├── 化物语 S01E09.nfo
│   ├── 化物语 S01E10-thumb.jpg
│   ├── 化物语 S01E10.mkv
│   ├── 化物语 S01E10.nfo
│   ├── 化物语 S01E11-thumb.jpg
│   ├── 化物语 S01E11.mkv
│   ├── 化物语 S01E11.nfo
│   ├── 化物语 S01E12-thumb.jpg
│   ├── 化物语 S01E12.mkv
│   ├── 化物语 S01E12.nfo
│   ├── 化物语 S01E13-thumb.jpg
│   ├── 化物语 S01E13.mkv
│   ├── 化物语 S01E13.nfo
│   ├── 化物语 S01E14-thumb.jpg
│   ├── 化物语 S01E14.mkv
│   ├── 化物语 S01E14.nfo
│   ├── 化物语 S01E15-thumb.jpg
│   ├── 化物语 S01E15.mkv
│   └── 化物语 S01E15.nfo
├── Season 10
│   ├── season.nfo
│   ├── 续·终物语 S10E01-thumb.jpg
│   ├── 续·终物语 S10E01.mkv
│   ├── 续·终物语 S10E01.nfo
│   ├── 续·终物语 S10E02-thumb.jpg
│   ├── 续·终物语 S10E02.mkv
│   ├── 续·终物语 S10E02.nfo
│   ├── 续·终物语 S10E03-thumb.jpg
│   ├── 续·终物语 S10E03.mkv
│   ├── 续·终物语 S10E03.nfo
│   ├── 续·终物语 S10E04-thumb.jpg
│   ├── 续·终物语 S10E04.mkv
│   ├── 续·终物语 S10E04.nfo
│   ├── 续·终物语 S10E05-thumb.jpg
│   ├── 续·终物语 S10E05.mkv
│   ├── 续·终物语 S10E05.nfo
│   ├── 续·终物语 S10E06-thumb.jpg
│   ├── 续·终物语 S10E06.mkv
│   └── 续·终物语 S10E06.nfo
├── Season 2
│   ├── season.nfo
│   ├── 伪物语 S02E01-thumb.jpg
│   ├── 伪物语 S02E01.mkv
│   ├── 伪物语 S02E01.nfo
│   ├── 伪物语 S02E02-thumb.jpg
│   ├── 伪物语 S02E02.mkv
│   ├── 伪物语 S02E02.nfo
│   ├── 伪物语 S02E03-thumb.jpg
│   ├── 伪物语 S02E03.mkv
│   ├── 伪物语 S02E03.nfo
│   ├── 伪物语 S02E04-thumb.jpg
│   ├── 伪物语 S02E04.mkv
│   ├── 伪物语 S02E04.nfo
│   ├── 伪物语 S02E05-thumb.jpg
│   ├── 伪物语 S02E05.mkv
│   ├── 伪物语 S02E05.nfo
│   ├── 伪物语 S02E06-thumb.jpg
│   ├── 伪物语 S02E06.mkv
│   ├── 伪物语 S02E06.nfo
│   ├── 伪物语 S02E07-thumb.jpg
│   ├── 伪物语 S02E07.mkv
│   ├── 伪物语 S02E07.nfo
│   ├── 伪物语 S02E08-thumb.jpg
│   ├── 伪物语 S02E08.mkv
│   ├── 伪物语 S02E08.nfo
│   ├── 伪物语 S02E09-thumb.jpg
│   ├── 伪物语 S02E09.mkv
│   ├── 伪物语 S02E09.nfo
│   ├── 伪物语 S02E10-thumb.jpg
│   ├── 伪物语 S02E10.mkv
│   ├── 伪物语 S02E10.nfo
│   ├── 伪物语 S02E11-thumb.jpg
│   ├── 伪物语 S02E11.mkv
│   └── 伪物语 S02E11.nfo
├── Season 3
│   ├── season.nfo
│   ├── 猫物语(黑) S03E01-thumb.jpg
│   ├── 猫物语(黑) S03E01.mkv
│   ├── 猫物语(黑) S03E01.nfo
│   ├── 猫物语(黑) S03E02-thumb.jpg
│   ├── 猫物语(黑) S03E02.mkv
│   ├── 猫物语(黑) S03E02.nfo
│   ├── 猫物语(黑) S03E03-thumb.jpg
│   ├── 猫物语(黑) S03E03.mkv
│   ├── 猫物语(黑) S03E03.nfo
│   ├── 猫物语(黑) S03E04-thumb.jpg
│   ├── 猫物语(黑) S03E04.mkv
│   └── 猫物语(黑) S03E04.nfo
├── Season 4
│   ├── season.nfo
│   ├── 物语系列 第二季 S04E01-thumb.jpg
│   ├── 物语系列 第二季 S04E01.mkv
│   ├── 物语系列 第二季 S04E01.nfo
│   ├── 物语系列 第二季 S04E02-thumb.jpg
│   ├── 物语系列 第二季 S04E02.mkv
│   ├── 物语系列 第二季 S04E02.nfo
│   ├── 物语系列 第二季 S04E03-thumb.jpg
│   ├── 物语系列 第二季 S04E03.mkv
│   ├── 物语系列 第二季 S04E03.nfo
│   ├── 物语系列 第二季 S04E04-thumb.jpg
│   ├── 物语系列 第二季 S04E04.mkv
│   ├── 物语系列 第二季 S04E04.nfo
│   ├── 物语系列 第二季 S04E05-thumb.jpg
│   ├── 物语系列 第二季 S04E05.mkv
│   ├── 物语系列 第二季 S04E05.nfo
│   ├── 物语系列 第二季 S04E06-thumb.jpg
│   ├── 物语系列 第二季 S04E06.mkv
│   ├── 物语系列 第二季 S04E06.nfo
│   ├── 物语系列 第二季 S04E07-thumb.jpg
│   ├── 物语系列 第二季 S04E07.mkv
│   ├── 物语系列 第二季 S04E07.nfo
│   ├── 物语系列 第二季 S04E08-thumb.jpg
│   ├── 物语系列 第二季 S04E08.mkv
│   ├── 物语系列 第二季 S04E08.nfo
│   ├── 物语系列 第二季 S04E09-thumb.jpg
│   ├── 物语系列 第二季 S04E09.mkv
│   ├── 物语系列 第二季 S04E09.nfo
│   ├── 物语系列 第二季 S04E10-thumb.jpg
│   ├── 物语系列 第二季 S04E10.mkv
│   ├── 物语系列 第二季 S04E10.nfo
│   ├── 物语系列 第二季 S04E11-thumb.jpg
│   ├── 物语系列 第二季 S04E11.mkv
│   ├── 物语系列 第二季 S04E11.nfo
│   ├── 物语系列 第二季 S04E12-thumb.jpg
│   ├── 物语系列 第二季 S04E12.mkv
│   ├── 物语系列 第二季 S04E12.nfo
│   ├── 物语系列 第二季 S04E13-thumb.jpg
│   ├── 物语系列 第二季 S04E13.mkv
│   ├── 物语系列 第二季 S04E13.nfo
│   ├── 物语系列 第二季 S04E14-thumb.jpg
│   ├── 物语系列 第二季 S04E14.mkv
│   ├── 物语系列 第二季 S04E14.nfo
│   ├── 物语系列 第二季 S04E15-thumb.jpg
│   ├── 物语系列 第二季 S04E15.mkv
│   ├── 物语系列 第二季 S04E15.nfo
│   ├── 物语系列 第二季 S04E16-thumb.jpg
│   ├── 物语系列 第二季 S04E16.mkv
│   ├── 物语系列 第二季 S04E16.nfo
│   ├── 物语系列 第二季 S04E17-thumb.jpg
│   ├── 物语系列 第二季 S04E17.mkv
│   ├── 物语系列 第二季 S04E17.nfo
│   ├── 物语系列 第二季 S04E18-thumb.jpg
│   ├── 物语系列 第二季 S04E18.mkv
│   ├── 物语系列 第二季 S04E18.nfo
│   ├── 物语系列 第二季 S04E19-thumb.jpg
│   ├── 物语系列 第二季 S04E19.mkv
│   ├── 物语系列 第二季 S04E19.nfo
│   ├── 物语系列 第二季 S04E20-thumb.jpg
│   ├── 物语系列 第二季 S04E20.mkv
│   ├── 物语系列 第二季 S04E20.nfo
│   ├── 物语系列 第二季 S04E21-thumb.jpg
│   ├── 物语系列 第二季 S04E21.mkv
│   ├── 物语系列 第二季 S04E21.nfo
│   ├── 物语系列 第二季 S04E22-thumb.jpg
│   ├── 物语系列 第二季 S04E22.mkv
│   ├── 物语系列 第二季 S04E22.nfo
│   ├── 物语系列 第二季 S04E23-thumb.jpg
│   ├── 物语系列 第二季 S04E23.mkv
│   └── 物语系列 第二季 S04E23.nfo
├── Season 5
│   ├── season.nfo
│   ├── 花物语 S05E01-thumb.jpg
│   ├── 花物语 S05E01.mkv
│   ├── 花物语 S05E01.nfo
│   ├── 花物语 S05E02-thumb.jpg
│   ├── 花物语 S05E02.mkv
│   ├── 花物语 S05E02.nfo
│   ├── 花物语 S05E03-thumb.jpg
│   ├── 花物语 S05E03.mkv
│   ├── 花物语 S05E03.nfo
│   ├── 花物语 S05E04-thumb.jpg
│   ├── 花物语 S05E04.mkv
│   ├── 花物语 S05E04.nfo
│   ├── 花物语 S05E05-thumb.jpg
│   ├── 花物语 S05E05.mkv
│   └── 花物语 S05E05.nfo
├── Season 6
│   ├── season.nfo
│   ├── 凭物语 S06E01-thumb.jpg
│   ├── 凭物语 S06E01.mkv
│   ├── 凭物语 S06E01.nfo
│   ├── 凭物语 S06E02-thumb.jpg
│   ├── 凭物语 S06E02.mkv
│   ├── 凭物语 S06E02.nfo
│   ├── 凭物语 S06E03-thumb.jpg
│   ├── 凭物语 S06E03.mkv
│   ├── 凭物语 S06E03.nfo
│   ├── 凭物语 S06E04-thumb.jpg
│   ├── 凭物语 S06E04.mkv
│   └── 凭物语 S06E04.nfo
├── Season 7
│   ├── season.nfo
│   ├── 终物语 S07E01-thumb.jpg
│   ├── 终物语 S07E01.mkv
│   ├── 终物语 S07E01.nfo
│   ├── 终物语 S07E02-thumb.jpg
│   ├── 终物语 S07E02.mkv
│   ├── 终物语 S07E02.nfo
│   ├── 终物语 S07E03-thumb.jpg
│   ├── 终物语 S07E03.mkv
│   ├── 终物语 S07E03.nfo
│   ├── 终物语 S07E04-thumb.jpg
│   ├── 终物语 S07E04.mkv
│   ├── 终物语 S07E04.nfo
│   ├── 终物语 S07E05-thumb.jpg
│   ├── 终物语 S07E05.mkv
│   ├── 终物语 S07E05.nfo
│   ├── 终物语 S07E06-thumb.jpg
│   ├── 终物语 S07E06.mkv
│   ├── 终物语 S07E06.nfo
│   ├── 终物语 S07E07-thumb.jpg
│   ├── 终物语 S07E07.mkv
│   ├── 终物语 S07E07.nfo
│   ├── 终物语 S07E08-thumb.jpg
│   ├── 终物语 S07E08.mkv
│   ├── 终物语 S07E08.nfo
│   ├── 终物语 S07E09-thumb.jpg
│   ├── 终物语 S07E09.mkv
│   ├── 终物语 S07E09.nfo
│   ├── 终物语 S07E10-thumb.jpg
│   ├── 终物语 S07E10.mkv
│   ├── 终物语 S07E10.nfo
│   ├── 终物语 S07E11-thumb.jpg
│   ├── 终物语 S07E11.mkv
│   ├── 终物语 S07E11.nfo
│   ├── 终物语 S07E12-thumb.jpg
│   ├── 终物语 S07E12.mkv
│   ├── 终物语 S07E12.nfo
│   ├── 终物语 S07E13-thumb.jpg
│   ├── 终物语 S07E13.mkv
│   ├── 终物语 S07E13.nfo
│   ├── 终物语 S07E14-thumb.jpg
│   ├── 终物语 S07E14.mkv
│   ├── 终物语 S07E14.nfo
│   ├── 终物语 S07E15-thumb.jpg
│   ├── 终物语 S07E15.mkv
│   ├── 终物语 S07E15.nfo
│   ├── 终物语 S07E16-thumb.jpg
│   ├── 终物语 S07E16.mkv
│   ├── 终物语 S07E16.nfo
│   ├── 终物语 S07E17-thumb.jpg
│   ├── 终物语 S07E17.mkv
│   ├── 终物语 S07E17.nfo
│   ├── 终物语 S07E18-thumb.jpg
│   ├── 终物语 S07E18.mkv
│   ├── 终物语 S07E18.nfo
│   ├── 终物语 S07E19-thumb.jpg
│   ├── 终物语 S07E19.mkv
│   ├── 终物语 S07E19.nfo
│   ├── 终物语 S07E20-thumb.jpg
│   ├── 终物语 S07E20.mkv
│   └── 终物语 S07E20.nfo
├── Season 8
│   ├── season.nfo
│   ├── 历物语 S08E01-thumb.jpg
│   ├── 历物语 S08E01.mkv
│   ├── 历物语 S08E01.nfo
│   ├── 历物语 S08E02-thumb.jpg
│   ├── 历物语 S08E02.mkv
│   ├── 历物语 S08E02.nfo
│   ├── 历物语 S08E03-thumb.jpg
│   ├── 历物语 S08E03.mkv
│   ├── 历物语 S08E03.nfo
│   ├── 历物语 S08E04-thumb.jpg
│   ├── 历物语 S08E04.mkv
│   ├── 历物语 S08E04.nfo
│   ├── 历物语 S08E05-thumb.jpg
│   ├── 历物语 S08E05.mkv
│   ├── 历物语 S08E05.nfo
│   ├── 历物语 S08E06-thumb.jpg
│   ├── 历物语 S08E06.mkv
│   ├── 历物语 S08E06.nfo
│   ├── 历物语 S08E07-thumb.jpg
│   ├── 历物语 S08E07.mkv
│   ├── 历物语 S08E07.nfo
│   ├── 历物语 S08E08-thumb.jpg
│   ├── 历物语 S08E08.mkv
│   ├── 历物语 S08E08.nfo
│   ├── 历物语 S08E09-thumb.jpg
│   ├── 历物语 S08E09.mkv
│   ├── 历物语 S08E09.nfo
│   ├── 历物语 S08E10-thumb.jpg
│   ├── 历物语 S08E10.mkv
│   ├── 历物语 S08E10.nfo
│   ├── 历物语 S08E11-thumb.jpg
│   ├── 历物语 S08E11.mkv
│   ├── 历物语 S08E11.nfo
│   ├── 历物语 S08E12-thumb.jpg
│   ├── 历物语 S08E12.mkv
│   └── 历物语 S08E12.nfo
├── Season 9
│   ├── season.nfo
│   ├── 伤物语 S09E01-thumb.jpg
│   ├── 伤物语 S09E01.mkv
│   ├── 伤物语 S09E01.nfo
│   ├── 伤物语 S09E02-thumb.jpg
│   ├── 伤物语 S09E02.mkv
│   ├── 伤物语 S09E02.nfo
│   ├── 伤物语 S09E03-thumb.jpg
│   ├── 伤物语 S09E03.mkv
│   └── 伤物语 S09E03.nfo
├── backdrop.jpg
├── banner.jpg
├── folder.jpg
├── logo.png
├── season01-poster.jpg
├── season02-poster.jpg
├── season03-poster.jpg
├── season04-poster.jpg
├── season05-poster.jpg
├── season06-poster.jpg
├── season07-poster.jpg
├── season08-poster.jpg
├── season09-poster.jpg
├── season10-poster.jpg
└── tvshow.nfo

11 directories, 334 files
```
I know I probably should have named it "物語系列 S09Exx", but I tried, and it doesn't change anything

**Comment by scampower3** [comment]
Hello, can you post the full log of when the error happen?

**Comment by 9bingyin** [comment]
I scanned the media library after removing Season 9 from the folder where the media library was located, then re-moved Season 9 back to the original file location, and scanned the media library again after that, and here is the log
```
[15:47:21] [INF] [90] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/media/Anime/物語系列/Season 9/伤物语 S09E01.mkv" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
Unsupported codec with id 98304 for input stream 8
Unsupported codec with id 98304 for input stream 9
Unsupported codec with id 98304 for input stream 10
Unsupported codec with id 98304 for input stream 11
Unsupported codec with id 98304 for input stream 12
[15:47:23] [ERR] [127] Jellyfin.Plugin.Tvdb.Providers.TvdbEpisodeProvider: Failed to retrieve episode with id 4139150, series id 0:伤物语 S09E01
System.ArgumentNullException: Value cannot be null. (Parameter 'person.Name')
   at System.ArgumentNullException.Throw(String paramName)
   at System.ArgumentNullException.ThrowIfNull(Object argument, String paramName)
   at System.ArgumentException.ThrowNullOrEmptyException(String argument, String paramName)
   at MediaBrowser.Controller.Entities.PeopleHelper.AddPerson(List`1 people, PersonInfo person)
   at Jellyfin.Plugin.Tvdb.Providers.TvdbEpisodeProvider.MapEpisodeToResult(EpisodeInfo id, EpisodeExtendedRecord episode, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Tvdb.Providers.TvdbEpisodeProvider.GetEpisode(EpisodeInfo searchInfo, CancellationToken cancellationToken, Boolean ignoreTvdbIdField)
[15:47:23] [INF] [127] Jellyfin.Server.Implementations.Trickplay.TrickplayManager: Creating trickplay files at 320 width, for /media/Anime/物語系列/Season 9/伤物语 S09E01.mkv [ID: 8dfc248b-575a-f3d8-0460-055b641e13c6]
[15:47:23] [INF] [127] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Trickplay generation: /usr/lib/jellyfin-ffmpeg/ffmpeg -loglevel error -init_hw_device vaapi=va:,kernel_driver=i915,driver=iHD -init_hw_device qsv=qs@va -filter_hw_device qs -hwaccel vaapi -hwaccel_output_format vaapi -noautorotate -i file:"/media/Anime/物語系列/Season 9/伤物语 S09E01.mkv" -noautoscale -an -sn -vf "fps=0.10000000149011612,setparams=color_primaries=bt709:color_trc=bt709:colorspace=bt709,scale_vaapi=w=320:h=136:format=nv12:extra_hw_frames=24,hwmap=derive_device=qsv,format=qsv" -threads 1 -c:v mjpeg_qsv -qscale:v 4 -f image2 "/cache/temp/ba915ae3321e4d799e97556ca367b55c/%08d.jpg"
libva info: VA-API version 1.21.0
libva info: Trying to open /usr/lib/jellyfin-ffmpeg/lib/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_21
libva info: va_openDriver() returns 0
libva info: VA-API version 1.21.0
libva info: Trying to open /usr/lib/jellyfin-ffmpeg/lib/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_21
libva info: va_openDriver() returns 0
[15:47:23] [INF] [127] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/media/Anime/物語系列/Season 9/伤物语 S09E02.mkv" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
Unsupported codec with id 98304 for input stream 8
Unsupported codec with id 98304 for input stream 9
Unsupported codec with id 98304 for input stream 10
Unsupported codec with id 98304 for input stream 11
Unsupported codec with id 98304 for input stream 12
Unsupported codec with id 98304 for input stream 13
[15:47:25] [ERR] [127] Jellyfin.Plugin.Tvdb.Providers.TvdbEpisodeProvider: Failed to retrieve episode with id 5356163, series id 0:伤物语 S09E02
System.ArgumentNullException: Value cannot be null. (Parameter 'person.Name')
   at System.ArgumentNullException.Throw(String paramName)
   at System.ArgumentNullException.ThrowIfNull(Object argument, String paramName)
   at System.ArgumentException.ThrowNullOrEmptyException(String argument, String paramName)
   at MediaBrowser.Controller.Entities.PeopleHelper.AddPerson(List`1 people, PersonInfo person)
   at Jellyfin.Plugin.Tvdb.Providers.TvdbEpisodeProvider.MapEpisodeToResult(EpisodeInfo id, EpisodeExtendedRecord episode, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Tvdb.Providers.TvdbEpisodeProvider.GetEpisode(EpisodeInfo searchInfo, CancellationToken cancellationToken, Boolean ignoreTvdbIdField)
[15:47:25] [INF] [90] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/media/Anime/物語系列/Season 9/伤物语 S09E03.mkv" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
Unsupported codec with id 98304 for input stream 8
Unsupported codec with id 98304 for input stream 9
Unsupported codec with id 98304 for input stream 10
Unsupported codec with id 98304 for input stream 11
Unsupported codec with id 98304 for input stream 12
Unsupported codec with id 98304 for input stream 13
[15:47:26] [ERR] [120] Jellyfin.Plugin.Tvdb.Providers.TvdbEpisodeProvider: Failed to retrieve episode with id 5356165, series id 0:伤物语 S09E03
System.ArgumentNullException: Value cannot be null. (Parameter 'person.Name')
   at System.ArgumentNullException.Throw(String paramName)
   at System.ArgumentNullException.ThrowIfNull(Object argument, String paramName)
   at System.ArgumentException.ThrowNullOrEmptyException(String argument, String paramName)
   at MediaBrowser.Controller.Entities.PeopleHelper.AddPerson(List`1 people, PersonInfo person)
   at Jellyfin.Plugin.Tvdb.Providers.TvdbEpisodeProvider.MapEpisodeToResult(EpisodeInfo id, EpisodeExtendedRecord episode, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Tvdb.Providers.TvdbEpisodeProvider.GetEpisode(EpisodeInfo searchInfo, CancellationToken cancellationToken, Boolean ignoreTvdbIdField)
```

**Comment by 9bingyin** [comment]
Maybe there are some other episodes with similar bugs, such as https://www.thetvdb.com/series/that-time-i-got-reincarnated-as-a-slime/episodes/9684711
```
[16:57:02] [INF] [34] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/media/Anime/关于我转生变成史莱姆这档事/Specials/Tensei Shitara Slime Datta Ken S00E11 柯里乌斯之梦 其二.mkv" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
[16:57:02] [ERR] [37] Jellyfin.Plugin.Tvdb.Providers.TvdbEpisodeProvider: Failed to retrieve episode with id 9684711, series id 9684711:Tensei Shitara Slime Datta Ken S00E11 柯里乌斯之梦 其二
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at Jellyfin.Plugin.Tvdb.Providers.TvdbEpisodeProvider.MapEpisodeToResult(EpisodeInfo id, EpisodeExtendedRecord episode, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Tvdb.Providers.TvdbEpisodeProvider.GetEpisode(EpisodeInfo searchInfo, CancellationToken cancellationToken, Boolean ignoreTvdbIdField)
[16:57:02] [ERR] [37] Jellyfin.Plugin.Tvdb.Providers.TvdbEpisodeImageProvider: Episode nullxnull not found for series 352408:关于我转生变成史莱姆这档事
```
