### ISSUE TITLE
Invalid seasons id

### ISSUE THREAD

**Issue by yayitazale** [jellyfin/jellyfin-plugin-tvdb#202]
I cannot search anything, I get always the same error:

```
Status: 400
Response: 
{"status":"failure","message":"InvalidValueType: cannot make item path","data":null}

   at Jellyfin.Plugin.Tvdb.SeasonClient.ExtendedSeasonClient.GetSeasonExtendedWithTranslationsAsync(Double id, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Tvdb.TvdbClientManager.GetSeasonByIdAsync(Int32 seasonTvdbId, String language, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Tvdb.Providers.TvdbSeasonImageProvider.GetSeasonArtworks(Int32 seriesTvdbId, Int32 seasonNumber, String displayOrder, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Tvdb.Providers.TvdbSeasonImageProvider.GetImages(BaseItem item, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.GetImages(BaseItem item, IRemoteImageProvider provider, String preferredLanguage, Boolean includeAllLanguages, CancellationToken cancellationToken, Nullable`1 type)
[2024-12-24 13:21:50.617 +01:00] [INF] [31] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/JF_SERIES/Monster (2022)/Season 2/Monster (2022) - S02E04 - Kill or be Killed WEBDL-1080p.mkv\" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format"
[2024-12-24 13:22:50.561 +01:00] [INF] [36] Jellyfin.Api.Controllers.ItemLookupController: Setting provider id's to item a5c67785-892b-ad55-4a92-9372a344fe0a-"Dance Monsters": [("Imdb": "tt13207736")]
[2024-12-24 13:22:52.358 +01:00] [ERR] [32] Emby.Server.Implementations.Library.LibraryManager: Cannot compute blurhash for "/config/metadata/library/36/36e54aed3a7929415eeedeb39eb53266/poster.png"
System.NullReferenceException: Object reference not set to an instance of an object.
   at BlurHashSharp.SkiaSharp.BlurHashEncoder.Encode(Int32 xComponent, Int32 yComponent, String filename, Int32 maxWidth, Int32 maxHeight)
   at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageBlurHash(Int32 xComp, Int32 yComp, String path)
   at Jellyfin.Drawing.ImageProcessor.GetImageBlurHash(String path, ImageDimensions imageDimensions)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)
[2024-12-24 13:22:53.482 +01:00] [ERR] [30] MediaBrowser.Providers.Manager.ProviderManager: "TvdbSeasonImageProvider" failed in GetImageInfos for type "Season" at "/JF_SERIES/Monster (2022)/Season 2"
HTTP Response: 

{"status":"failure","message":"InvalidValueType: cannot make item path","data":null}
```

**Comment by RedNo7** [comment]
I have the same problem.
