### ISSUE TITLE
Jellyfin and thetvdb API not working

### ISSUE THREAD

**Issue by eycer1995** [jellyfin/jellyfin-plugin-tvdb#48]
Recently I set up a Jellyfin server with a RPi4 mainly used to watch anime. After using it a few months with AniDB I didn't like the way it organizes the anime, so I want to switch to thetvdb.

HW: RPi4
Version 10.7.6
OS: Raspbian

Since it wasn't working with the default API from the tvdb plugin **I paid the tvdb subscription** to get my own "Legacy API key" like they called it thinking that may be the problem, but after changing the API key still can't get any metadata from the tvdb. 

 What am I doing wrong?

I'm following the naming scheme of tvdb for my anime library.

I also tried to manually identifying the anime with thetvdb ID but only got synopsis and the cast info, not the images.

Is the problem Jellyfin? Thetvdb? me? Any suggestions? Please help.

The logs show this:

```
[2021-08-22 23:56:24.477 -03:00] [ERR] "TvdbSeriesImageProvider" failed in GetImageInfos for type "Series" at "/mnt/external/shared/Jellyfin/Anime test/Oreimo (2010)" TvDbSharper.TvDbServerException: The given series ID does not exist; Resource not found

at TvDbSharper.Infrastructure.Parser.Parse[T](ApiResponse response, IReadOnlyDictionary`2 errorMap)

at TvDbSharper.Clients.SeriesClient.GetImagesSummaryAsync(Int32 seriesId, CancellationToken cancellationToken)

at Jellyfin.Plugin.Tvdb.TvdbClientManager.<>c__DisplayClass24_0`1.<<TryGetValue>b__0>d.MoveNext() --- End of stack trace from previous location ---

at Microsoft.Extensions.Caching.Memory.CacheExtensions.GetOrCreateAsync[TItem](IMemoryCache cache, Object key, Func`2 factory)

at Jellyfin.Plugin.Tvdb.TvdbClientManager.GetImageKeyTypesForSeriesAsync(Int32 tvdbId, String language, CancellationToken cancellationToken)+MoveNext()

at Jellyfin.Plugin.Tvdb.TvdbClientManager.GetImageKeyTypesForSeriesAsync(Int32 tvdbId, String language, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()

at Jellyfin.Plugin.Tvdb.Providers.TvdbSeriesImageProvider.GetImages(BaseItem item, CancellationToken cancellationToken)

at Jellyfin.Plugin.Tvdb.Providers.TvdbSeriesImageProvider.GetImages(BaseItem item, CancellationToken cancellationToken)

at MediaBrowser.Providers.Manager.ProviderManager.GetImages(BaseItem item, IRemoteImageProvider provider, IReadOnlyCollection`1 preferredLanguages, CancellationToken cancellationToken, Nullable`1 type)

[2021-08-22 23:56:24.670 -03:00] [ERR] "TvdbSeasonImageProvider" failed in GetImageInfos for type "Season" at "/mnt/external/shared/Jellyfin/Anime test/Oreimo (2010)/Season 1" TvDbSharper.TvDbServerException: The given series ID does not exist; Resource not found

at TvDbSharper.Infrastructure.Parser.Parse[T](ApiResponse response, IReadOnlyDictionary`2 errorMap)

at TvDbSharper.Clients.SeriesClient.GetImagesSummaryAsync(Int32 seriesId, CancellationToken cancellationToken)

at Jellyfin.Plugin.Tvdb.TvdbClientManager.<>c__DisplayClass24_0`1.<<TryGetValue>b__0>d.MoveNext() --- End of stack trace from previous location ---

at Microsoft.Extensions.Caching.Memory.CacheExtensions.GetOrCreateAsync[TItem](IMemoryCache cache, Object key, Func`2 factory)

at Jellyfin.Plugin.Tvdb.TvdbClientManager.GetImageKeyTypesForSeasonAsync(Int32 tvdbId, String language, CancellationToken cancellationToken)+MoveNext()

at Jellyfin.Plugin.Tvdb.TvdbClientManager.GetImageKeyTypesForSeasonAsync(Int32 tvdbId, String language, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()

at Jellyfin.Plugin.Tvdb.Providers.TvdbSeasonImageProvider.GetImages(BaseItem item, CancellationToken cancellationToken)

at Jellyfin.Plugin.Tvdb.Providers.TvdbSeasonImageProvider.GetImages(BaseItem item, CancellationToken cancellationToken)

at MediaBrowser.Providers.Manager.ProviderManager.GetImages(BaseItem item, IRemoteImageProvider provider, IReadOnlyCollection`1 preferredLanguages, CancellationToken cancellationToken, Nullable`1 type)

[2021-08-22 23:56:24.769 -03:00] [ERR] "TvdbSeasonImageProvider" failed in GetImageInfos for type "Season" at "/mnt/external/shared/Jellyfin/Anime test/Oreimo (2010)/Specials" TvDbSharper.TvDbServerException: The given series ID does not exist; Resource not found

at TvDbSharper.Infrastructure.Parser.Parse[T](ApiResponse response, IReadOnlyDictionary`2 errorMap)

at TvDbSharper.Clients.SeriesClient.GetImagesSummaryAsync(Int32 seriesId, CancellationToken cancellationToken)

at Jellyfin.Plugin.Tvdb.TvdbClientManager.<>c__DisplayClass24_0`1.<<TryGetValue>b__0>d.MoveNext() --- End of stack trace from previous location ---

at Microsoft.Extensions.Caching.Memory.CacheExtensions.GetOrCreateAsync[TItem](IMemoryCache cache, Object key, Func`2 factory)

at Jellyfin.Plugin.Tvdb.TvdbClientManager.GetImageKeyTypesForSeasonAsync(Int32 tvdbId, String language, CancellationToken cancellationToken)+MoveNext()

at Jellyfin.Plugin.Tvdb.TvdbClientManager.GetImageKeyTypesForSeasonAsync(Int32 tvdbId, String language, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()

at Jellyfin.Plugin.Tvdb.Providers.TvdbSeasonImageProvider.GetImages(BaseItem item, CancellationToken cancellationToken)

at Jellyfin.Plugin.Tvdb.Providers.TvdbSeasonImageProvider.GetImages(BaseItem item, CancellationToken cancellationToken)

at MediaBrowser.Providers.Manager.ProviderManager.GetImages(BaseItem item, IRemoteImageProvider provider, IReadOnlyCollection`1 preferredLanguages, CancellationToken cancellationToken, Nullable`1 type)

[2021-08-22 23:56:24.869 -03:00] [ERR] "TvdbSeasonImageProvider" failed in GetImageInfos for type "Season" at "/mnt/external/shared/Jellyfin/Anime test/Oreimo (2010)/Season 2" TvDbSharper.TvDbServerException: The given series ID does not exist; Resource not found

at TvDbSharper.Infrastructure.Parser.Parse[T](ApiResponse response, IReadOnlyDictionary`2 errorMap)

at TvDbSharper.Clients.SeriesClient.GetImagesSummaryAsync(Int32 seriesId, CancellationToken cancellationToken)

at Jellyfin.Plugin.Tvdb.TvdbClientManager.<>c__DisplayClass24_0`1.<<TryGetValue>b__0>d.MoveNext() --- End of stack trace from previous location ---

at Microsoft.Extensions.Caching.Memory.CacheExtensions.GetOrCreateAsync[TItem](IMemoryCache cache, Object key, Func`2 factory)

at Jellyfin.Plugin.Tvdb.TvdbClientManager.GetImageKeyTypesForSeasonAsync(Int32 tvdbId, String language, CancellationToken cancellationToken)+MoveNext()

at Jellyfin.Plugin.Tvdb.TvdbClientManager.GetImageKeyTypesForSeasonAsync(Int32 tvdbId, String language, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()

at Jellyfin.Plugin.Tvdb.Providers.TvdbSeasonImageProvider.GetImages(BaseItem item, CancellationToken cancellationToken)

at Jellyfin.Plugin.Tvdb.Providers.TvdbSeasonImageProvider.GetImages(BaseItem item, CancellationToken cancellationToken)

at MediaBrowser.Providers.Manager.ProviderManager.GetImages(BaseItem item, IRemoteImageProvider provider, IReadOnlyCollection`1 preferredLanguages, CancellationToken cancellationToken, Nullable`1 type)
```

**Comment by crobibero** [comment]
@ontheflow your issue is different from the original issue. Yours has `Resource temporarily unavailable (api.thetvdb.com:443)`. This means that TheTVDB's API went down, and there's nothing we can do to fix that.

**Comment by ontheflow** [comment]
@crobibero maybe i tried to often,  i will try again in a few days

**Comment by ontheflow** [comment]
> @crobibero maybe i tried to often, i will try again in a few days

Switching from MacVlan to Host in Docker solved my Problem
