### ISSUE TITLE
Unhelpful error messages

### ISSUE THREAD

**Issue by michaelkrieger** [jellyfin/jellyfin-plugin-tvdb#71]
Exceptions, like the one shown below, don’t provide the series ID in question. This debugging the problem and identifying a possibly misclassified show or episode is difficult.  A helpful error message on these exceptions with information on what it was processing at the time would resolve this

```
[2022-05-07 09:45:03.088 -04:00] [WRN] [26] Jellyfin.Plugin.Tvdb.Providers.TvdbMissingEpisodeProvider: Unable to get episodes from TVDB
TvDbSharper.TvDbServerException: The given series ID does not exist; No results for your query: map[AiredSeason:8]
   at TvDbSharper.Infrastructure.Parser.Parse[T](ApiResponse response, IReadOnlyDictionary`2 errorMap)
   at TvDbSharper.Clients.SeriesClient.GetEpisodesAsync(Int32 seriesId, Int32 page, EpisodeQuery query, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Tvdb.TvdbClientManager.<>c__DisplayClass24_0`1.<<TryGetValue>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Extensions.Caching.Memory.CacheExtensions.GetOrCreateAsync[TItem](IMemoryCache cache, Object key, Func`2 factory)
   at Jellyfin.Plugin.Tvdb.Providers.TvdbMissingEpisodeProvider.GetAllEpisodes(Int32 tvdbId, String acceptedLanguage, EpisodeQuery episodeQuery)
```

**Comment by eric1905** [comment]
I saw the same error messages in my log file and would be glad to get a hint in the log which path is processed and which series id is used to check in tvdb
