### ISSUE TITLE
Creating and improperly handling skipped season numbers.

### ISSUE THREAD

**Issue by michaelkrieger** [jellyfin/jellyfin-plugin-tvdb#73]
A good example of this is [Beavis & Butthead](https://thetvdb.com/series/beavis-and-butt-head) where TheTVDB has skipped Season 8 (as MTV skipped Season 8 in their marketing).

1. It should not keep recreating the absent Season 8 which does not exist in TheTVDB.  It is not missing and should not be in Jellyfin.
2. It should further not throw a giant unhelpful warning which doesn't explicitly state which series is even being queried for Season 8.

I keep getting a "missing" season 8 created each time.  There is no Season 8 for the plugin to keep creating.

Jellyfin TVDB Missing plugin produces the following error.

```
[2022-05-26 13:59:36.118 -04:00] [INF] [63] Jellyfin.Plugin.Tvdb.Providers.TvdbMissingEpisodeProvider: Creating Season "Season 8" entry for "Beavis and Butt-Head"
[2022-05-26 13:59:36.414 -04:00] [WRN] [48] Jellyfin.Plugin.Tvdb.Providers.TvdbMissingEpisodeProvider: Unable to get episodes from TVDB
TvDbSharper.TvDbServerException: The given series ID does not exist; No results for your query: map[AiredSeason:8]
   at TvDbSharper.Infrastructure.Parser.Parse[T](ApiResponse response, IReadOnlyDictionary`2 errorMap)
   at TvDbSharper.Clients.SeriesClient.GetEpisodesAsync(Int32 seriesId, Int32 page, EpisodeQuery query, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Tvdb.TvdbClientManager.<>c__DisplayClass24_0`1.<<TryGetValue>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Extensions.Caching.Memory.CacheExtensions.GetOrCreateAsync[TItem](IMemoryCache cache, Object key, Func`2 factory)
   at Jellyfin.Plugin.Tvdb.Providers.TvdbMissingEpisodeProvider.GetAllEpisodes(Int32 tvdbId, String acceptedLanguage, EpisodeQuery episodeQuery)
```

**Comment by maddoglee** [comment]
any response to this? I am finding it difficult to identify which series ID is missing as well....
