### ISSUE TITLE
API issue

### ISSUE THREAD

**Issue by eagleeyetom** [jellyfin/jellyfin-plugin-tvdb#78]
Hi!

While refreshing the metadata I keep getting a bunch of the following errors.

```
[2022-08-02 20:47:57.445 +02:00] [ERR] Failed to retrieve episode with id null, series id null
TvDbSharper.TvDbServerException: Invalid credentials; API Key Required
   at TvDbSharper.Infrastructure.Parser.Parse[T](ApiResponse response, IReadOnlyDictionary`2 errorMap)
   at TvDbSharper.Clients.AuthenticationClient.AuthenticateAsync(AuthenticationData authenticationData, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Tvdb.TvdbClientManager.GetTvDbClient(String language)
   at Jellyfin.Plugin.Tvdb.TvdbClientManager.<>c__DisplayClass24_0`1.<<TryGetValue>b__0>d.MoveNext()
--- End of stack trace from previous location ---
```

Jellyfin 10.8.3, arm64, Debian

**Comment by crobibero** [comment]
We provide and API key by default. Did you happen to change it?

**Comment by eagleeyetom** [comment]
I haven't changed it. I was migrating from one device to another by moving the /var/lib/jellyfin folder. Could you hint to me where to check the currently used API?

**Comment by eagleeyetom** [comment]
Ok, my bad. I have reinstalled the plugin and it works as intended. Thanks!
